version: '3.8'

services:
  web:
    build: .
    container_name: sgo_web
    restart: always
    env_file:
      - .env
    volumes:
      # Preparamos la carpeta local ./data para almacenar los futuros PDFs generados
      - ./data:/app/data
    # No exponemos el puerto 8000 hacia afuera, solo hacia nginx dentro de la red interna
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: sgo_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
