"""Add reference to Offer

Revision ID: 16352df3ee65
Revises: 655409cec431
Create Date: 2026-04-27 14:26:20.338293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16352df3ee65'
down_revision: Union[str, Sequence[str], None] = '655409cec431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_offers_reference'), 'offers', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_reference'), table_name='offers')
    # ### end Alembic commands ###
