"""rename_fields

Revision ID: 655409cec431
Revises: 
Create Date: 2026-04-22 02:31:33.050791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655409cec431'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'ip_address', new_column_name='investigador_principal')
    op.alter_column('clients', 'internal_account', new_column_name='cuenta_interna')
    op.alter_column('clients', 'project_id', new_column_name='codigo_proyecto')
    op.alter_column('clients', 'group_name', new_column_name='grupo')
    
    op.alter_column('clients', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
               
    op.alter_column('service_catalog', 'price1', new_column_name='price_internal')
    op.alter_column('service_catalog', 'price2', new_column_name='price_csic')
    op.alter_column('service_catalog', 'price3', new_column_name='price_public')
    op.alter_column('service_catalog', 'price4', new_column_name='price_private')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_catalog', 'price_internal', new_column_name='price1')
    op.alter_column('service_catalog', 'price_csic', new_column_name='price2')
    op.alter_column('service_catalog', 'price_public', new_column_name='price3')
    op.alter_column('service_catalog', 'price_private', new_column_name='price4')

    op.alter_column('clients', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
               
    op.alter_column('clients', 'investigador_principal', new_column_name='ip_address')
    op.alter_column('clients', 'cuenta_interna', new_column_name='internal_account')
    op.alter_column('clients', 'codigo_proyecto', new_column_name='project_id')
    op.alter_column('clients', 'grupo', new_column_name='group_name')
    # ### end Alembic commands ###
