"""make reference unique

Revision ID: c603ec6addeb
Revises: 16352df3ee65
Create Date: 2026-04-29 13:23:17.325979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c603ec6addeb'
down_revision: Union[str, Sequence[str], None] = '16352df3ee65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_reference'), table_name='offers')
    op.create_index(op.f('ix_offers_reference'), 'offers', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_reference'), table_name='offers')
    op.create_index(op.f('ix_offers_reference'), 'offers', ['reference'], unique=False)
    # ### end Alembic commands ###
